@server=http://localhost:4004
@service=/odata/v4/products

### Products
POST {{server}}{{service}}/Products
Content-Type: application/json
Accept: */*

{
  "Code": "100",
  "Name": "Iphone XI",
  "Description": "Celular Iphone com 128GB",
  "Price": 1500.00,
  "Supplier": "Apple INC."
}

### Products
GET {{server}}{{service}}/Products
Content-Type: application/json
Accept: */*

### Products by ID
GET {{server}}{{service}}/Products/234c06b3-ab44-45cb-a2b8-986f4f5e4b1b
Content-Type: application/json
Accept: */*

### Products
PUT {{server}}{{service}}/Products/234c06b3-ab44-45cb-a2b8-986f4f5e4b1b
Content-Type: application/json
Accept: */*

{
  "Code": "101",
  "Name": "Iphone XI",
  "Description": "Celular Iphone com 128GB",
  "Price": 1500.00,
  "Supplier": "Apple INC."
}

### Products
DELETE {{server}}{{service}}/Products/234c06b3-ab44-45cb-a2b8-986f4f5e4b1b
Content-Type: application/json
Accept: */*

